FROM python:3.11-slim
WORKDIR /Ajouter
RUN useradd -m appuser
COPY . .

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest

USER appuser

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]