FROM python:3.11-slim
WORKDIR /Ajouter

COPY . .

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


USER appuser

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]