version: '3.8'

services:


  affichage:
    build :  
      context: ./API/Affichage  
      dockerfile: dockerfile
    container_name: affichage
    networks:
      - backend
    environment:
      - MONGO_URI=mongodb://172.17.32.196:27017/colis_db
    depends_on:
      - mongo
    ports:
      - "8000:8000"



  ajouter:
    build: 
      context: ./API/Ajouter 
      dockerfile: dockerfile
    container_name: ajouter
    networks:
      - backend
    environment:
      - MONGO_URI=mongodb://172.17.32.196:27017/colis_db
    depends_on:
      - mongo
    ports:
      - "8001:8001"
    

  auth:
    build:       
      context: ./API/Auth
      dockerfile: dockerfile
    container_name: auth
    networks:
      - backend
    environment:
      - MONGO_URI=mongodb://172.17.32.196:27017/colis_db
    depends_on:
      - mongo
    ports:
      - "8002:8002"

  
  mongo:
    image: mongo:latest
    container_name: mongodb
    networks :
      - backend
      - base
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=colis_db
    ports:
      - "27017:27017"



  



  web:
    build: 
      context: ./flask_app
      dockerfile: dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=${cnx}
      - API_AFFICHAGE_URL=${cnxaffichage}
      - API_AJOUTER_URL=${cnxajouter}
      - API_AUTH_URL=${cnxauth}
    depends_on:
      - mongo
      - affichage
      - ajouter
      - auth


volumes:
  mongo_data:


networks:
  backend:
  base:


