FROM python:3.9-slim

WORKDIR /flask_app
RUN useradd -m appuser

COPY . .

RUN pip install pytest
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
USER appuser
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]