FROM python:3.9-slim

WORKDIR /flask_app

COPY . .
COPY requirements.txt .
RUN pip install pytest


RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]