server {
    listen 80;
    server_name web.com;

    location /Affichage {
        proxy_pass http://localhost:8000;
    }
        location /Ajouter {
        proxy_pass http://localhost:8001;
    }
        location /Affichage {
        proxy_pass http://localhost:8002;
    }
}
