FROM python:3.11-slim
WORKDIR /Auth
COPY . .



RUN pip install pytest
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
